name: AIBattery
options:
  deploymentTarget:
    macOS: "13.0"
  bundleIdPrefix: com.KyleNesium
  xcodeVersion: "16.0"
  createIntermediateGroups: true

targets:
  AIBattery:
    type: application
    platform: macOS
    sources:
      - path: AIBattery
    info:
      path: AIBattery/Info.plist
      properties:
        LSUIElement: true
        CFBundleDisplayName: AI Battery
        CFBundleName: AI Battery
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.KyleNesium.AIBattery
        MARKETING_VERSION: "1.4.0"
        CURRENT_PROJECT_VERSION: "12"
        SWIFT_VERSION: "5.9"
        MACOSX_DEPLOYMENT_TARGET: "13.0"
        CODE_SIGN_STYLE: Automatic
        CODE_SIGN_IDENTITY: "-"
        INFOPLIST_KEY_LSUIElement: true
    entitlements:
      path: AIBattery/AIBattery.entitlements
      properties:
        com.apple.security.app-sandbox: false
