name: Bug Report
description: Something isn't working as expected
labels: [bug]
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      placeholder: A clear description of what's happening.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. Open AI Battery
        2. Click ...
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      placeholder: What you expected to happen.

  - type: dropdown
    id: macos
    attributes:
      label: macOS version
      options:
        - macOS 15 (Sequoia)
        - macOS 14 (Sonoma)
        - macOS 13 (Ventura)
    validations:
      required: true

  - type: dropdown
    id: plan
    attributes:
      label: Claude Code plan
      options:
        - Free
        - Pro
        - Teams
        - Max
        - Max (5x)
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Drag and drop any relevant screenshots here.
