name: Feature Request
description: Suggest a new feature or improvement
labels: [enhancement]
body:
  - type: textarea
    id: problem
    attributes:
      label: What problem does this solve?
      placeholder: Describe the use case or pain point.
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      placeholder: How you'd like it to work.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      placeholder: Any other approaches you've thought about.

  - type: textarea
    id: context
    attributes:
      label: Additional context
      placeholder: Screenshots, mockups, or links to related issues.
