import SwiftUI

struct TokenUsageSection: View {
    let snapshot: UsageSnapshot
    var activeModelId: String? = nil
    @AppStorage(UserDefaultsKeys.showCostEstimate) private var showCost: Bool = false

    private let modelIcons = [
        "cpu", "bolt", "sparkles", "cube", "wand.and.stars"
    ]

    /// Sort: active model first, then by total tokens descending.
    private var sortedTokens: [ModelTokenSummary] {
        guard let activeId = activeModelId, !activeId.isEmpty else {
            return snapshot.modelTokens
        }
        var sorted = snapshot.modelTokens
        if let idx = sorted.firstIndex(where: { activeId.hasPrefix($0.id) || $0.id.hasPrefix(activeId) }) {
            let active = sorted.remove(at: idx)
            sorted.insert(active, at: 0)
        }
        return sorted
    }

    private func isActive(_ model: ModelTokenSummary) -> Bool {
        guard let activeId = activeModelId, !activeId.isEmpty else { return false }
        return activeId.hasPrefix(model.id) || model.id.hasPrefix(activeId)
    }

    var body: some View {
        VStack(alignment: .leading, spacing: 8) {
            // Header: total tokens + optional cost
            HStack {
                Text("Tokens")
                    .font(.subheadline.bold())
                    .help("Total tokens used across all models")
                if showCost {
                    let total = ModelPricing.totalCost(for: snapshot.modelTokens)
                    Text(ModelPricing.formatCost(total))
                        .font(.system(.caption, design: .monospaced))
                        .foregroundStyle(.secondary)
                        .copyable(ModelPricing.formatCost(total))
                }
                Spacer()
                Text(TokenFormatter.format(snapshot.totalTokens))
                    .font(.system(.subheadline, design: .monospaced, weight: .semibold))
                    .copyable(TokenFormatter.format(snapshot.totalTokens))
            }

            // Per-model breakdown with token types underneath
            if !snapshot.modelTokens.isEmpty {
                ForEach(Array(sortedTokens.enumerated()), id: \.element.id) { index, model in
                    VStack(alignment: .leading, spacing: 4) {
                        // Model row
                        HStack(spacing: 6) {
                            Image(systemName: modelIcons[index % modelIcons.count])
                                .font(.system(size: 10))
                                .foregroundStyle(.secondary)
                                .frame(width: 14)

                            Text(model.displayName)
                                .font(.caption)
                                .lineLimit(1)

                            if isActive(model) {
                                Text("▶")
                                    .font(.caption2)
                                    .foregroundStyle(.green)
                                    .help("Active model in current session")
                                    .accessibilityLabel("Active")
                            }

                            Spacer()

                            if showCost, let pricing = ModelPricing.pricing(for: model.id) {
                                let modelCost = pricing.cost(
                                    input: model.inputTokens,
                                    output: model.outputTokens,
                                    cacheRead: model.cacheReadTokens,
                                    cacheWrite: model.cacheWriteTokens
                                )
                                Text(ModelPricing.formatCost(modelCost))
                                    .font(.system(.caption2, design: .monospaced))
                                    .foregroundStyle(.tertiary)
                                    .copyable(ModelPricing.formatCost(modelCost))
                            }

                            Text(TokenFormatter.format(model.totalTokens))
                                .font(.system(.caption, design: .monospaced))
                                .foregroundStyle(.secondary)
                                .copyable(TokenFormatter.format(model.totalTokens))
                        }

                        // Token type breakdown for this model
                        HStack(spacing: 10) {
                            Spacer()
                                .frame(width: 14)
                            TokenTag(icon: "arrow.up", label: TokenFormatter.format(model.inputTokens), accessibilityName: "input", tooltip: "Input tokens sent to Claude")
                            TokenTag(icon: "arrow.down", label: TokenFormatter.format(model.outputTokens), accessibilityName: "output", tooltip: "Output tokens generated by Claude")
                            TokenTag(icon: "doc.on.doc", label: TokenFormatter.format(model.cacheReadTokens), accessibilityName: "cache read", tooltip: "Cached tokens reused (cheaper)")
                            TokenTag(icon: "square.and.pencil", label: TokenFormatter.format(model.cacheWriteTokens), accessibilityName: "cache write", tooltip: "Tokens written to prompt cache")
                            Spacer()
                        }
                    }
                    .accessibilityElement(children: .combine)
                    .accessibilityLabel("\(model.displayName), \(TokenFormatter.format(model.totalTokens)) tokens: \(TokenFormatter.format(model.inputTokens)) input, \(TokenFormatter.format(model.outputTokens)) output, \(TokenFormatter.format(model.cacheReadTokens)) cache read, \(TokenFormatter.format(model.cacheWriteTokens)) cache write")
                }
            }
        }
        .padding(.horizontal, 16)
        .padding(.vertical, 12)
    }
}

private struct TokenTag: View {
    let icon: String
    let label: String
    var accessibilityName: String = ""
    var tooltip: String = ""

    var body: some View {
        HStack(spacing: 2) {
            Image(systemName: icon)
                .font(.system(size: 8))
                .foregroundStyle(.secondary.opacity(0.7))
            Text(label)
                .font(.system(.caption2, design: .monospaced))
                .foregroundStyle(.secondary.opacity(0.7))
        }
        .accessibilityLabel("\(accessibilityName) \(label)")
        .help(tooltip)
    }
}
